# Adds the fields required for vector classification (Topic.description),
# the SEEED encyclopaedia link (Prompt.seeed_url), classifier confidence on
# NotRelevantReport, the EngagementEvent model, and allows Prompt.triggers to
# be blank (prompts no longer require triggers once the classifier is primary).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0003_alter_trigger_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True, help_text="A rich semantic description used by the vector classifier. Recommended format: 'This content covers topics related to [topic]: [key concepts], [example user queries], [contrast with adjacent topics].' The better this captures how users actually phrase queries, the better the matching. Topics without a description fall back to '[group]: [name]' for matching, which is much weaker."),
        ),
        migrations.AddField(
            model_name='prompt',
            name='seeed_url',
            field=models.URLField(blank=True, null=True, max_length=500, verbose_name='SEEED URL', help_text="Link to the corresponding SEEED encyclopaedia entry, once it exists. When set, the prompt card in the extension shows a 'Learn more' link."),
        ),
        migrations.AddField(
            model_name='notrelevantreport',
            name='classifier_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='triggers',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='researchdata.trigger'),
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('prompt_shown', 'Prompt shown'), ('prompt_expanded', 'Prompt expanded'), ('prompt_dismissed', 'Prompt dismissed'), ('learn_more_clicked', 'SEEED link clicked'), ('response_submitted', 'Response submitted'), ('not_relevant_reported', 'Not relevant reported'), ('badge_shown', 'AI Mode badge shown'), ('badge_opened', 'AI Mode badge opened')], max_length=32)),
                ('session_key', models.CharField(blank=True, help_text='Random per-installation identifier generated by the extension. Not linked to any personal data.', max_length=64)),
                ('serp_mode', models.CharField(blank=True, help_text="Which Google layout the event occurred in: 'classic' or 'ai'.", max_length=16)),
                ('classifier_confidence', models.FloatField(blank=True, null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.prompt')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.topic')),
            ],
            options={'ordering': ['-meta_created_datetime']},
        ),
    ]
