# Generated by Django 5.2.15 on 2026-06-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0004_vector_classification_and_seeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text="A research topic/theme that prompts are organised into, e.g. 'US Election 2024' (which would belong to the 'Politics' topic group).", max_length=255, unique=True),
        ),
    ]
