# Generated by Django 5.2.15 on 2026-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0005_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='trigger_text',
            field=models.TextField(help_text="A word or phrase that will trigger a prompt to the user. Must match exactly to user's search term.", unique=True),
        ),
    ]
