# Generated by Django 5.2.15 on 2026-07-09 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0006_alter_trigger_trigger_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.TextField()),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='ContentApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('dry_run', models.BooleanField(default=True)),
                ('created_counts', models.JSONField(default=dict)),
                ('updated_counts', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_applies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content apply',
                'verbose_name_plural': 'content applies',
                'ordering': ('-created_datetime',),
            },
        ),
    ]
