# Generated by Django 5.2.16 on 2026-07-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0007_content_apply_and_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('git_sha', models.CharField(blank=True, max_length=40)),
                ('model_id', models.CharField(blank=True, max_length=255)),
                ('model_artifact', models.CharField(blank=True, help_text='Hash and size of the ONNX file actually loaded (the filename is always model.onnx).', max_length=120)),
                ('runtime', models.CharField(blank=True, help_text='onnxruntime version, CPU architecture and Python version that produced the scores.', max_length=120)),
                ('index_fingerprint', models.CharField(blank=True, max_length=64)),
                ('labelled_file', models.CharField(blank=True, max_length=255)),
                ('scorer', models.CharField(default='production', help_text='Which ranking function produced the scores (production, or a named ablation).', max_length=64)),
                ('threshold', models.FloatField()),
                ('margin', models.FloatField(default=0.0)),
                ('metrics', models.JSONField(default=dict)),
                ('results', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_datetime',),
            },
        ),
    ]
